// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUb1PR2nOKO_H2ZuAiO-3GGNYGhsNZYvk',
    appId: '1:184600721978:web:955675eaa9f40a49d91303',
    messagingSenderId: '184600721978',
    projectId: 'aplicacion-de-prueba-80d41',
    authDomain: 'aplicacion-de-prueba-80d41.firebaseapp.com',
    storageBucket: 'aplicacion-de-prueba-80d41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJGXERzxDH-ONXNMItMcyGb9NP02EXQ0',
    appId: '1:184600721978:android:ef61d1f8fd487351d91303',
    messagingSenderId: '184600721978',
    projectId: 'aplicacion-de-prueba-80d41',
    storageBucket: 'aplicacion-de-prueba-80d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1a8fXYQaJAjpy9jFaoXnqd1RLJNu7a7w',
    appId: '1:184600721978:ios:69888d980d6ae1dad91303',
    messagingSenderId: '184600721978',
    projectId: 'aplicacion-de-prueba-80d41',
    storageBucket: 'aplicacion-de-prueba-80d41.firebasestorage.app',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1a8fXYQaJAjpy9jFaoXnqd1RLJNu7a7w',
    appId: '1:184600721978:ios:69888d980d6ae1dad91303',
    messagingSenderId: '184600721978',
    projectId: 'aplicacion-de-prueba-80d41',
    storageBucket: 'aplicacion-de-prueba-80d41.firebasestorage.app',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUb1PR2nOKO_H2ZuAiO-3GGNYGhsNZYvk',
    appId: '1:184600721978:web:99ba5aa12e364f51d91303',
    messagingSenderId: '184600721978',
    projectId: 'aplicacion-de-prueba-80d41',
    authDomain: 'aplicacion-de-prueba-80d41.firebaseapp.com',
    storageBucket: 'aplicacion-de-prueba-80d41.firebasestorage.app',
  );
}
